const SCHEMA={occlusion:['none','partial','heavy'],lighting:['bright','normal','low-light'],orientation:['upright','rotated','inverted'],environment:['bench','floor'],result:['success','failure'],recovery:['no','yes']};
const seedSpecs=[
 ['none','normal','upright','bench','success','no'],['none','normal','upright','bench','success','no'],['none','normal','upright','floor','success','no'],['none','normal','upright','bench','success','no'],['none','normal','rotated','bench','success','no'],['none','normal','upright','floor','success','no'],['none','normal','upright','bench','success','no'],['none','normal','upright','bench','success','no'],['none','normal','rotated','floor','success','no'],['none','normal','upright','bench','success','no'],['none','normal','upright','floor','success','no'],['none','normal','upright','bench','success','no'],['none','normal','upright','bench','success','no'],['none','normal','rotated','floor','success','no'],['partial','normal','upright','bench','failure','no'],['partial','low-light','upright','bench','failure','no'],['partial','low-light','upright','floor','success','no'],['none','low-light','upright','bench','success','no'],['none','bright','rotated','floor','success','no'],['none','bright','upright','bench','success','no']
];
const seed=seedSpecs.map((x,i)=>({id:`seed-${i+1}`,created:Date.now()-i*1000,source:'seed',occlusion:x[0],lighting:x[1],orientation:x[2],environment:x[3],result:x[4],recovery:x[5]}));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let clips=[], recommendation, stream, recorder, chunks=[], seconds=0, ticker, sampleTicker, recordedBlob, proposedTags, frameMetrics=[];

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('trace-store',1);r.onupgradeneeded=()=>r.result.createObjectStore('clips',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function load(){try{const db=await openDB();clips=await new Promise((res,rej)=>{const q=db.transaction('clips').objectStore('clips').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});if(!clips.length){clips=seed;await Promise.all(seed.map(saveRecord))}}catch{clips=[...seed];toast('Private mode: using session storage')} render()}
async function saveRecord(row){try{const db=await openDB();await new Promise((res,rej)=>{const q=db.transaction('clips','readwrite').objectStore('clips').put(row);q.onsuccess=res;q.onerror=()=>rej(q.error)})}catch{}}
async function reset(){try{const db=await openDB();await new Promise(r=>{const q=db.transaction('clips','readwrite').objectStore('clips').clear();q.onsuccess=r});clips=[...seed];await Promise.all(seed.map(saveRecord))}catch{clips=[...seed]}render();toast('Demo dataset restored')}

function combinations(){const a=[];for(const occlusion of SCHEMA.occlusion)for(const lighting of SCHEMA.lighting)for(const orientation of SCHEMA.orientation)for(const environment of SCHEMA.environment)a.push({occlusion,lighting,orientation,environment});return a}
function scoreAll(){const failures=clips.filter(c=>c.result==='failure');const maxCount=Math.max(1,...combinations().map(x=>countExact(x)));return combinations().map(x=>{const count=countExact(x);const gap=1-count/maxCount;const overlaps=failures.map(f=>['occlusion','lighting','orientation','environment'].filter(k=>f[k]===x[k]).length/4);const failure=overlaps.length?overlaps.reduce((a,b)=>a+b,0)/overlaps.length:0;const novelty=Math.min(1,.35+gap*.6);const costs={none:1,partial:1.15,heavy:1.5,bright:1.1,normal:1,'low-light':1.2,upright:1,rotated:1.15,inverted:1.45,bench:1,floor:1.1};const cost=(costs[x.occlusion]+costs[x.lighting]+costs[x.orientation]+costs[x.environment])/4;const priority=(.3*gap+.5*failure+.2*novelty)/cost;return{...x,count,gap,failure,novelty,cost,priority}}).sort((a,b)=>b.priority-a.priority)}
function countExact(x){return clips.filter(c=>Object.keys(x).every(k=>c[k]===x[k])).length}
function analyze(){return scoreAll()[0]}
function pct(n){return `${Math.round(n*100)}%`}
function title(v){return v.replace('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function instructionFor(x){const recoveryGap=clips.filter(c=>c.recovery==='yes').length/clips.length<.1;return `Record a ${x.occlusion}ly occluded pick of a ${x.orientation} object in ${x.lighting} conditions${recoveryGap?' — continue through any failed grasp to capture recovery': ''}.`}
function coverage(){const contextKeys=['occlusion','lighting','orientation','environment'];const categoryCoverage=contextKeys.reduce((sum,key)=>sum+new Set(clips.map(c=>c[key])).size/SCHEMA[key].length,0)/contextKeys.length;const occupied=new Set(clips.map(c=>contextKeys.map(k=>c[k]).join('|'))).size;const comboCoverage=occupied/combinations().length;const outcomeCoverage=(new Set(clips.map(c=>c.result)).size/SCHEMA.result.length+new Set(clips.map(c=>c.recovery)).size/SCHEMA.recovery.length)/2;return Math.round(100*(.45*categoryCoverage+.35*comboCoverage+.2*outcomeCoverage))}

function render(){recommendation=analyze();$('#instruction').textContent=instructionFor(recommendation);const failures=clips.filter(c=>c.result==='failure');const matching=failures.filter(f=>['occlusion','lighting','orientation','environment'].filter(k=>f[k]===recommendation[k]).length>=2).length;$('#rationale').textContent=`${matching} of ${failures.length} logged failures overlap this context. It has ${recommendation.count} examples, producing a ${pct(recommendation.gap)} gap score; the ranking is recomputed from the current store.`;$('#failureScore').textContent=pct(recommendation.failure);$('#gapScore').textContent=pct(recommendation.gap);$('#priorityScore').textContent=recommendation.priority.toFixed(2);$('#coverage').textContent=coverage();const recoveries=clips.filter(c=>c.recovery==='yes').length;$('#datasetSummary').textContent=`${clips.filter(c=>c.occlusion==='none').length} of ${clips.length} clips are unobstructed. ${failures.length} failures logged. ${recoveries} ${recoveries===1?'clip contains':'clips contain'} recovery.`;renderFailures(failures);renderMap();$('#captureTarget').textContent=instructionFor(recommendation)}
function renderFailures(failures){$('#failureCards').innerHTML=failures.slice(0,3).map((f,i)=>`<div class="failureCard"><b>Failure ${String(i+1).padStart(2,'0')}</b><span>${f.occlusion.toUpperCase()}</span><small>${title(f.lighting)} · ${title(f.orientation)} · No recovery</small></div>`).join('')||'<p class="lede">No failures logged yet.</p>'}
function renderMap(){const dims=['occlusion','lighting','orientation','recovery'];$('#coverageMap').innerHTML=dims.flatMap(dim=>SCHEMA[dim].map(val=>{const count=clips.filter(c=>c[dim]===val).length;const fails=clips.filter(c=>c[dim]===val&&c.result==='failure').length;const width=Math.max(3,count/clips.length*100);return `<div class="bar ${fails?'danger':''}"><span>${title(val)}</span><div class="barTrack"><div class="barFill" style="width:${width}%"></div></div><b>${count}${fails?` / ${fails}F`:''}</b></div>`})).join('');$('#failureLog').innerHTML=clips.filter(c=>c.result==='failure').map(c=>`<div class="logItem"><b>${title(c.occlusion)} occlusion · ${title(c.lighting)}</b><small>${title(c.orientation)} · ${title(c.environment)} · ${c.recovery==='yes'?'Recovery captured':'No recovery'}</small></div>`).join('')}

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('navActive',b.dataset.view===id));scrollTo(0,0)}
async function beginCapture(){showView('captureView');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280}},audio:true});$('#preview').srcObject=stream;$('#modelStatus').textContent='CAMERA + LOCAL VISION'}catch(e){toast('Camera permission is required');showView('homeView')}}
function endCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;clearInterval(ticker);clearInterval(sampleTicker);seconds=0;$('#timer').textContent='00:00'}
function sampleFrame(){const v=$('#preview'),c=$('#sample'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=96;c.height=72;try{ctx.drawImage(v,0,0,c.width,c.height);const p=ctx.getImageData(0,0,c.width,c.height).data,g=[];let sum=0,sq=0,gx=0,gy=0,center=0,centerSq=0,centerN=0,bottom=0,top=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const i=(y*c.width+x)*4,val=(p[i]+p[i+1]+p[i+2])/3;g.push(val);sum+=val;sq+=val*val;if(y<c.height/3)top+=val;if(y>=c.height*2/3)bottom+=val;if(x>24&&x<72&&y>18&&y<54){center+=val;centerSq+=val*val;centerN++}if(x)gx+=Math.abs(val-g[g.length-2]);if(y)gy+=Math.abs(val-g[g.length-c.width-1])}const n=g.length,mean=sum/n,variance=sq/n-mean*mean,cMean=center/centerN,cVar=centerSq/centerN-cMean*cMean,prev=frameMetrics.at(-1)?.pixels,motion=prev?g.reduce((a,v,i)=>a+Math.abs(v-prev[i]),0)/n:0;frameMetrics.push({mean,variance,cVar,gx:gx/n,gy:gy/n,verticalBias:(bottom-top)/(n/3),motion,pixels:g})}catch{}}
function toggleRecording(){if(recorder?.state==='recording'){recorder.stop();return}if(!stream)return;chunks=[];frameMetrics=[];sampleFrame();sampleTicker=setInterval(sampleFrame,500);recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'});recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{clearInterval(sampleTicker);sampleFrame();recordedBlob=new Blob(chunks,{type:recorder.mimeType});analyzeFrames();endCamera();showView('reviewView')};recorder.start();$('#recordBtn').classList.add('recording');$('#recState').textContent='RECORDING';ticker=setInterval(()=>{seconds++;$('#timer').textContent=`00:${String(seconds).padStart(2,'0')}`;if(seconds>=8)recorder.stop()},1000)}
function analyzeFrames(){const frames=frameMetrics.length?frameMetrics:[{mean:110,variance:900,cVar:700,gx:10,gy:12,verticalBias:0,motion:0}];const avg=k=>frames.reduce((s,f)=>s+f[k],0)/frames.length;const mean=avg('mean'),textureRatio=avg('cVar')/Math.max(1,avg('variance')),motions=frames.map(f=>f.motion),motionMean=motions.reduce((a,b)=>a+b,0)/motions.length,peaks=motions.slice(1,-1).filter((m,i)=>m>motions[i]*1.35&&m>motions[i+2]*1.35&&m>6).length;proposedTags={occlusion:textureRatio<.32?'heavy':textureRatio<.68?'partial':'none',lighting:mean<70?'low-light':mean>175?'bright':'normal',orientation:avg('gx')>avg('gy')*1.18?'rotated':avg('gy')>avg('gx')*1.6?'inverted':'upright',environment:avg('verticalBias')>12?'floor':'bench',result:motions.at(-1)>Math.max(8,motionMean*1.35)?'failure':'success',recovery:peaks>=2?'yes':'no'};renderTagEditor();$('#processBar').style.width='100%';setTimeout(()=>{$('#processState').textContent=`${frames.length} KEYFRAMES · LOCAL MOTION + VISION FEATURES`;$('#saveClip').disabled=false},900)}
function renderTagEditor(){$('#tagEditor').innerHTML=Object.entries(SCHEMA).map(([key,vals])=>`<div class="tagRow"><label>${key.toUpperCase()} · PROPOSED</label><div class="tagOptions">${vals.map(v=>`<button class="${proposedTags[key]===v?'selected':''}" data-key="${key}" data-value="${v}">${title(v)}</button>`).join('')}</div></div>`).join('');$$('.tagOptions button').forEach(b=>b.onclick=()=>{proposedTags[b.dataset.key]=b.dataset.value;renderTagEditor()})}
async function commitClip(){const before=coverage();const row={id:`live-${Date.now()}`,created:Date.now(),source:'live',...proposedTags,video:recordedBlob};clips.push(row);await saveRecord(row);render();$('#oldCoverage').textContent=`${before}%`;$('#newCoverage').textContent=`${coverage()}%`;$('#successCopy').textContent=`A ${proposedTags.occlusion}-occlusion, ${proposedTags.orientation} pick tagged ${proposedTags.result}${proposedTags.recovery==='yes'?' with recovery':''} is now evidence. TRACE re-ranked every candidate from the updated store.`;showView('successView')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#recordThis').onclick=beginCapture;$('#quickRecord').onclick=beginCapture;$('#closeCapture').onclick=()=>{endCamera();showView('homeView')};$('#recordBtn').onclick=toggleRecording;$('#saveClip').onclick=commitClip;$('#discardClip').onclick=()=>{recordedBlob=null;showView('homeView')};$('#resetBtn').onclick=reset;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();
